"""
Hand-crafted city stories — event-driven, fact-checked.
Each story: a data observation + a plausible explanation.
Assumptions are clearly framed as inferences, not proven causation.
"""

CITY_STORIES = {
    "delhi": {
        "narrative": "Delhi's spring air is a rollercoaster — the city swung between 16 and 167 µg/m³ over these 6 weeks. PM2.5 exceeded the WHO limit on every single day. According to a DPCC/IIT Kanpur real-time source apportionment study, dust accounts for 52.5% of Delhi's PM2.5 in summer — making it the dominant driver. CAQM invoked GRAP Stage-I on Apr 16, unusual for April. Rain is the only reliable cleanup mechanism — a single convective storm on Apr 17 crashed PM2.5 to 16 overnight, before dust resuspension drove it back to 167 the next day.",
        "stories": [
            {
                "event": "Month opened at 142 µg/m³ — 9x the safe limit",
                "dates": "Mar 10–12",
                "impact": "PM2.5 hit 142 µg/m³ on the first day — the worst reading of the entire month.",
                "detail": "A DPCC/IIT Kanpur study (2023) found dust accounts for 52.5% of Delhi's summer PM2.5 — the single largest source. Vehicle exhaust contributes 8-12% year-round. March is peak dust season as westerly winds carry particles from Rajasthan (IQAir, Down to Earth). No specific dust storm was reported on these dates — this likely reflects Delhi's elevated spring baseline rather than a discrete event.",
                "sources": ["DPCC/IIT Kanpur (2023)", "IQAir", "Down to Earth"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-12",
            },
            {
                "event": "PM2.5 doubled on Holi night",
                "dates": "Mar 14",
                "impact": "PM2.5 jumped from 58 to 119 µg/m³ overnight — doubling in a single day.",
                "detail": "Holi was celebrated on Mar 14, with Holika Dahan bonfires the night before (StayVista). Bonfires and firecrackers are known PM2.5 sources during festivals — but Delhi also sees 50-100% daily swings routinely in spring. The timing is suggestive but we cannot isolate Holi's contribution from background dust variability.",
                "sources": ["Holi 2026 on Mar 14 (StayVista)"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-13",
                "end": "2026-03-14",
            },
            {
                "event": "Best air quality in 161 days — AQI hit 93",
                "dates": "Mar 19",
                "impact": "PM2.5 dropped to 29 µg/m³. AQI hit 93 — first 'Satisfactory' rating since October 2025.",
                "detail": "Overnight rain from a western disturbance was reported by Outlook Traveller and NewsX. Rain physically removes particles from the air (wet deposition — well-established atmospheric science). The Patriot confirmed AQI dropped to 93. The western disturbance was unusual for its timing — a 1,000 km rain band, per Legacy IAS. The correlation between rain and PM2.5 drop is consistent with known scavenging mechanisms.",
                "sources": ["Outlook Traveller", "NewsX", "The Patriot"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-18",
                "end": "2026-03-19",
            },
            {
                "event": "PM2.5 climbed back to 126 over 4 dry days",
                "dates": "Mar 23–25",
                "impact": "PM2.5 hit 126 on Mar 23 and stayed above 100 for 3 straight days.",
                "detail": "After the Mar 19 rain, conditions returned to dry spring normal. No specific event was identified for this spike — it likely reflects the resumption of Delhi's background pollution (dust resuspension, traffic, construction) once rain-based suppression ended. This pattern of 'rain relief → rapid rebound' repeated multiple times this month.",
                "sources": [],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-23",
                "end": "2026-03-25",
            },
            {
                "event": "AQI crossed 500 during dust storm",
                "dates": "Apr 1–2",
                "impact": "PM10 exceeded 800 µg/m³. Delhi ranked among the world's 10 most polluted cities.",
                "detail": "IQAir reported on Apr 3 that AQI exceeded 500, driven overwhelmingly by coarse dust (PM10 > 800 µg/m³). PM10 dominating over PM2.5 is the signature of a dust transport event — consistent with the DPCC finding that dust is 52.5% of summer PM2.5. Satellite aerosol imagery from NASA Worldview (MODIS) can independently verify the dust plume path for this date.",
                "sources": ["IQAir (Apr 3, 2026)", "AQI.in", "DPCC/IIT Kanpur source apportionment"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-01",
                "end": "2026-04-02",
            },
            {
                "event": "Coldest April day in 11 years — AQI dropped to 93",
                "dates": "Apr 8",
                "impact": "Temperature hit 28.2°C — 6.9°C below normal. AQI dropped to 93.",
                "detail": "Oneindia and Daily Pioneer confirmed the temperature record and AQI reading. Rain and wind from a western disturbance likely dispersed pollutants — consistent with wet deposition and mechanical dispersion mechanisms. By Apr 9, dust was back at 105 µg/m³, suggesting the cleanup was entirely weather-driven and temporary.",
                "sources": ["Oneindia", "Daily Pioneer", "Skymet Weather"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-07",
                "end": "2026-04-08",
            },
            {
                "event": "PM2.5 swung 80 µg/m³ in 24 hours",
                "dates": "Apr 9–10",
                "impact": "PM2.5 crashed from 105 to 58 overnight — a 45% single-day drop.",
                "detail": "The Air Quality Early Warning System forecast winds of 22-26 kmph on Apr 10. Wind-driven dispersion of particulate matter is well-established physics. The Patriot described Delhi's spring AQI as 'dangerously volatile' — this single-day swing illustrates the pattern. No rain was reported, so mechanical dispersion by wind is the most likely mechanism. The relief was short-lived — dust rebuilt over the next 3 days.",
                "sources": ["AQI.in", "The Patriot", "Air Quality EWS"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-09",
                "end": "2026-04-10",
            },
            {
                "event": "Dust and heat triggered GRAP Stage I — rare for April",
                "dates": "Apr 14–16",
                "impact": "PM2.5 averaged 144 µg/m³ over 3 days, peaking at 165. PM10 hit 499. AQI reached 226 (Poor) on Apr 16.",
                "detail": "The Week reported CAQM invoked GRAP Stage-I on Apr 16 — unusual for April when GRAP is typically off. Max temperature was 40.3°C on Apr 15 with winds under 10 kmph, trapping pollutants near the ground (thermal inversion is a known accumulation mechanism). IQAir ranked Delhi among the top 10 most polluted cities globally on Apr 15. The dominant driver was dust (PM10 > PM2.5 ratio), consistent with the DPCC finding that dust is 52.5% of Delhi's summer PM2.5.",
                "sources": ["The Week (Apr 17, 2026)", "IQAir", "CAQM/DPCC"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-14",
                "end": "2026-04-16",
            },
            {
                "event": "Storm crashed PM2.5 to 16 — cleanest day in 6 weeks",
                "dates": "Apr 17",
                "impact": "PM2.5 plunged from 164 to 16 µg/m³ in 24 hours — the cleanest reading of the entire period.",
                "detail": "Business League reported an intense convective storm on the night of Apr 17 with 60 kmph winds, heavy rain, and lightning; flights were diverted at IGI. Asianet Newsable and Sunday Guardian confirmed a western disturbance brought rain, winds, and a temperature drop to Delhi-NCR. Rain scavenging plus wind dispersion together produced the dramatic drop — the single most effective natural cleanup mechanism. The relief lasted less than 24 hours.",
                "sources": ["Business League", "Asianet Newsable", "Sunday Guardian (IMD)"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-17",
                "end": "2026-04-17",
            },
            {
                "event": "Dust resuspension spiked PM2.5 to 167 the next morning",
                "dates": "Apr 18",
                "impact": "PM2.5 rebounded from 16 to 167 in 24 hours — a 944% single-day jump, the worst reading of the period.",
                "detail": "RealShePower reported residents woke to a surprisingly hazy morning on Apr 18. The CSR Journal described a heavy dust storm affecting Delhi-NCR air quality. Strong storm winds on Apr 17 night lifted settled dust back into the air — a well-documented post-storm resuspension pattern in arid regions. The same western disturbance that cleaned the air on Apr 17 mobilised dust that descended on Apr 18 once winds calmed.",
                "sources": ["RealShePower", "The CSR Journal"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-18",
                "end": "2026-04-18",
            },
        ],
    },
    "bengaluru": {
        "narrative": "Bengaluru's air is 2.3x the safe limit — moderate by Indian standards but never actually safe. CPCB source apportionment attributes 28% to vehicle exhaust and 23% to dust/construction. The 6 weeks saw a hailstorm that briefly cleaned the air, a mysterious one-day spike to 60 µg/m³, and steadily weakening volatility as pre-monsoon showers established in April. Even the cleanest day (17 µg/m³) was above WHO limits — but April was notably calmer than March.",
        "stories": [
            {
                "event": "PM2.5 hit 48 during dry mid-March spell",
                "dates": "Mar 12–15",
                "impact": "PM2.5 hit 48 µg/m³ on Mar 13 — 3.2x the safe limit. Humidity dropped from 65% to 50%.",
                "detail": "CPCB source apportionment for Bengaluru attributes 23% of PM2.5 to dust and construction. Citizen Matters documented that Namma Metro Phase 2 construction is happening in residential areas without proper dust management. AQI.in recorded PM2.5 of 52 on Mar 13. Declining humidity (65% → 50%) reduces natural moisture suppression — a known mechanism. However, we cannot isolate metro construction from other dust sources on these specific dates.",
                "sources": ["CPCB/UrbanEmissions", "Citizen Matters", "AQI.in"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-12",
                "end": "2026-03-15",
            },
            {
                "event": "Hailstorm on Mar 17, then 3 days of cleaner air",
                "dates": "Mar 17–20",
                "impact": "PM2.5 spiked to 46 during the storm, then dropped to 28 over the following days.",
                "detail": "Deccan Herald reported hail in Sanjayanagar, Yelahanka, and Devanahalli on Mar 17. Zee News confirmed IMD thunderstorm warnings for Mar 17-21. The post-storm PM2.5 decline is consistent with rain scavenging — wet deposition is the most effective natural particle removal mechanism. Ugadi was celebrated Mar 19 which may have reduced weekday traffic, though this effect is difficult to quantify.",
                "sources": ["Deccan Herald", "Zee News (IMD)"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-17",
                "end": "2026-03-20",
            },
            {
                "event": "Month's worst day — PM2.5 hit 60, then fell back",
                "dates": "Mar 23–24",
                "impact": "PM2.5 spiked to 60 µg/m³ (4x the safe limit) then dropped to 36 overnight.",
                "detail": "No specific event was identified for this one-day anomaly. The spike was recorded across 39 stations city-wide, which suggests a regional phenomenon (like a dust transport event or atmospheric stagnation) rather than a single local source. Without wind trajectory data or satellite imagery, we cannot determine the cause.",
                "sources": [],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-23",
                "end": "2026-03-24",
            },
            {
                "event": "4 days below average during pre-monsoon showers",
                "dates": "Apr 1–4",
                "impact": "PM2.5 averaged 31 µg/m³ — still 2x the safe limit, but the cleanest sustained stretch.",
                "detail": "Oneindia reported 90-100% thunderstorm probability as pre-monsoon convective season established over Karnataka. IMD Bengaluru forecast light to moderate rain. Intermittent showers are consistent with the sustained low PM2.5 — repeated rain events prevent particle accumulation. This seasonal pattern is well-documented for south India.",
                "sources": ["Oneindia", "IMD Bengaluru"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-01",
                "end": "2026-04-04",
            },
            {
                "event": "PM2.5 spiked on IPL match day",
                "dates": "Apr 5",
                "impact": "PM2.5 jumped from 32 to 43 µg/m³ — the only spike in an otherwise clean week.",
                "detail": "RCB vs CSK was played at Chinnaswamy Stadium (confirmed by IPLT20). News9 and Goodreturns reported police banned parking on MG Road and Queens Road and issued a traffic advisory. Increased traffic is a plausible contributor to the PM2.5 spike, as NO2 (a traffic marker) tends to correlate with match-day congestion. However, we cannot isolate the match's effect from other daily variability — a 11 µg/m³ jump is within Bengaluru's normal range.",
                "sources": ["IPLT20", "News9", "Goodreturns"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-05",
                "end": "2026-04-05",
            },
            {
                "event": "35.2°C heatwave — yet PM2.5 hit month's low",
                "dates": "Apr 7",
                "impact": "Bengaluru recorded its lowest PM2.5 of the month (17 µg/m³ — near WHO safe levels) on one of its hottest days.",
                "detail": "NewsFirst Prime confirmed 35.2°C (1.5°C above normal) on this date. Deccan Herald reported IMD predicted rising heat with rain relief from Apr 11. Counter-intuitively, strong surface heating can increase vertical mixing, lifting pollutants away from ground level — a well-known meteorological mechanism. This may explain why the hottest day had the cleanest air, though other factors (wind patterns, reduced activity) could also contribute.",
                "sources": ["NewsFirst Prime", "Deccan Herald"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-07",
                "end": "2026-04-07",
            },
            {
                "event": "11 days of stable air as pre-monsoon season set in",
                "dates": "Apr 11–21",
                "impact": "PM2.5 stayed in a narrow 25–36 µg/m³ band for 11 straight days — the least volatile stretch of the period.",
                "detail": "Oneindia reported pre-monsoon showers arriving with 90-100% thunderstorm probability. Deccan Herald described evening showers bringing relief from summer heat. Repeated small rain events prevent dust accumulation (wet deposition). RCB played home games at Chinnaswamy on Apr 15 (vs LSG) and Apr 18 (vs DC) with fans 'braving scorching heat' per Deccan Herald, but no match-day PM2.5 anomaly was visible above the baseline.",
                "sources": ["Oneindia", "Deccan Herald", "ESPNcricinfo"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-11",
                "end": "2026-04-21",
            },
        ],
    },
    "hyderabad": {
        "narrative": "Hyderabad's air is the steadiest of the 6 cities — 2.1x the WHO limit with less day-to-day volatility than Delhi or Jaipur. Unseasonal rain around Ugadi gave the longest clean stretch of the month, and a second thunderstorm system on Apr 19 produced another one-day dip. Between rain events, construction dust kept pollution at 2–2.5x the safe limit.",
        "stories": [
            {
                "event": "Month's highest PM2.5 during dry mid-March",
                "dates": "Mar 12–15",
                "impact": "PM2.5 averaged 37 µg/m³ — the highest sustained stretch of the month.",
                "detail": "IMD via PingTV reported temperatures of 32-37°C across Telangana with no rain during this period. Dry conditions reduce natural wet deposition and allow dust to remain airborne longer — a well-established relationship. However, this was a modest elevation (6 µg/m³ above mean) and may simply reflect normal variability rather than a specific event.",
                "sources": ["IMD via PingTV"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-12",
                "end": "2026-03-15",
            },
            {
                "event": "Week of cleaner air around Ugadi and unseasonal rain",
                "dates": "Mar 16–22",
                "impact": "PM2.5 dropped to 22 µg/m³ on Mar 16 and stayed low for 7 days.",
                "detail": "PingTV reported unseasonal rains with lightning and gusty winds (41-61 kmph) sweeping through Telangana around Mar 17. Hyderabad Mail confirmed Ugadi celebrations on Mar 19. Rain scavenging is the most likely explanation for the sustained low PM2.5. Reduced weekday activity during Ugadi may have contributed, though the rain effect alone is sufficient to explain the pattern.",
                "sources": ["PingTV", "Hyderabad Mail"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-16",
                "end": "2026-03-22",
            },
            {
                "event": "PM2.5 hit 44 as residents reported construction dust",
                "dates": "Mar 28–30",
                "impact": "PM2.5 jumped to 44 µg/m³ — 2.9x the safe limit. AQI hit 146 on Mar 27.",
                "detail": "AQI.in recorded AQI of 146 (Poor) on Mar 27. Hyderabad Mail reported residents near Golconda Chowrasta complained of severe dust from Gentry Homes construction, with elderly and children facing respiratory problems. While construction dust is a documented PM contributor, other sources (traffic, regional dust) likely also contributed. The resident complaints provide direct ground-level evidence of dust as a factor.",
                "sources": ["AQI.in", "Hyderabad Mail"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-28",
                "end": "2026-03-30",
            },
            {
                "event": "Steadier air through early April after late-March rain",
                "dates": "Mar 31 – Apr 7",
                "impact": "PM2.5 averaged 27 µg/m³ for a week — no dramatic spikes.",
                "detail": "Sunday Guardian and IMD reported late evening thundershowers around end of March. The week-long stable pattern is consistent with regular moisture input suppressing dust resuspension. April showed less volatility than March across most Indian cities, which is typical as pre-monsoon convective activity increases.",
                "sources": ["Sunday Guardian", "IMD"],
                "confirmed": False,
                "type": "dip",
                "start": "2026-03-31",
                "end": "2026-04-07",
            },
            {
                "event": "Thunderstorm cut PM2.5 nearly in half on Apr 19",
                "dates": "Apr 19",
                "impact": "PM2.5 dropped to 20 µg/m³ on Apr 19 — the cleanest day of the period — after hovering around 34–37 for a week.",
                "detail": "Sakshi Post and Deccan Chronicle reported IMD forecast rain relief in Hyderabad from Apr 19 with thunderstorm warnings for Telangana over the following four days. PingTV India confirmed rain in Hyderabad broke the heatwave. Rain scavenging is the most effective natural particle removal mechanism — the timing of the PM2.5 drop matches the storm arrival exactly. By Apr 20, dust had rebuilt to 36 µg/m³, following the familiar 'rain relief → rapid rebound' pattern.",
                "sources": ["Sakshi Post", "Deccan Chronicle", "PingTV India"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-19",
                "end": "2026-04-19",
            },
        ],
    },
    "mumbai": {
        "narrative": "Mumbai had three clear phases. Early March was dirty (PM2.5 up to 48, driven by construction). Rain arrived Mar 28 and the air became extraordinarily clean — AQI hit 21 on Mar 31. Dry heat brought it back from April 9. A pan-India pre-monsoon spell Apr 15–17 cleaned the air again before overnight dust surges returned the city to 35–41 µg/m³ by Apr 21.",
        "stories": [
            {
                "event": "PM2.5 at 44 despite BMC crackdown on 1,073 sites",
                "dates": "Mar 10–13",
                "impact": "PM2.5 averaged 44 µg/m³ despite enforcement. Hotspots: Kanjurmarg AQI 309, Ghatkopar 183.",
                "detail": "Deccan Herald and Free Press Journal reported BMC issued stop-work notices to 1,073 construction sites violating dust-control norms. PM2.5 was down 14% year-on-year per Deccan Herald, suggesting enforcement had some effect. However, PM2.5 remained 3x the safe limit — indicating construction dust is one of many contributors. A Newslaundry investigation found Mumbai had only 7 'good' air days in 5 years, calling the chronic pollution 'normalised.'",
                "sources": ["Deccan Herald", "Free Press Journal", "Newslaundry"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-13",
            },
            {
                "event": "PM2.5 crept from 13 to 48 over 10 dry days",
                "dates": "Mar 17–26",
                "impact": "PM2.5 rose gradually from 13 to 48 µg/m³ over 10 days.",
                "detail": "After a brief clean spell, pollution steadily rebuilt as dry weather returned. Free Press Journal noted AQI reached 89 (Moderate) by Mar 27 — described as 'a major improvement compared to previous weeks.' The gradual nature of the rise suggests accumulation from persistent sources (construction, traffic) rather than a single event. This pattern — slow buildup interrupted only by rain — is characteristic of Mumbai's spring pollution.",
                "sources": ["Free Press Journal"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-17",
                "end": "2026-03-26",
            },
            {
                "event": "AQI hit 21 — below WHO safe limit for 12 days",
                "dates": "Mar 28 – Apr 8",
                "impact": "PM2.5 dropped to 10 µg/m³ — below the WHO safe limit. AQI hit 21 on Mar 31.",
                "detail": "Free Press Journal reported AQI of 21 (Good) on Mar 31 and predicted light rain bringing relief from heat. Rain scavenging is the most effective natural particle removal mechanism, and the sustained clean period (12 days) is consistent with repeated rain events suppressing dust. Mumbai's coastal geography also helps — onshore sea breezes push pollutants inland during wet weather.",
                "sources": ["Free Press Journal"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-28",
                "end": "2026-04-08",
            },
            {
                "event": "PM2.5 surged to 43 as dry heat returned",
                "dates": "Apr 9–10",
                "impact": "PM2.5 surged to 43 µg/m³ by Apr 10 — the highest since late March. Navi Mumbai AQI hit 201.",
                "detail": "AQI.in recorded Mumbai AQI of 100 (Moderate) on Apr 10 and Navi Mumbai at 201 (Severe). IQAir ranked Mumbai among the most polluted cities globally on Apr 9. The spike coincided with the end of rain and return of dry conditions — consistent with the cessation of wet deposition allowing particle accumulation. The clean spell lasted exactly as long as the rain did.",
                "sources": ["AQI.in", "IQAir"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-09",
                "end": "2026-04-10",
            },
            {
                "event": "Pre-monsoon spell dropped PM2.5 back below 21",
                "dates": "Apr 15–17",
                "impact": "PM2.5 averaged 20 µg/m³ over 3 days — back below half the Indian NAAQS limit.",
                "detail": "Sunday Guardian's Apr 16 weather report documented a pan-India pre-monsoon spell driven by a western disturbance, Bay of Bengal moisture, and a wind discontinuity — with rain predictions across Delhi NCR, Mumbai, Chennai, Karnataka, Rajasthan, and Hyderabad. The IMD all-India bulletin confirmed the system. Mumbai's coastal geography amplifies the cleanup — onshore sea breezes push pollutants inland while rain scavenges particulates.",
                "sources": ["Sunday Guardian (IMD)", "IMD All-India Weather Bulletin"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-15",
                "end": "2026-04-17",
            },
            {
                "event": "PM2.5 doubled overnight as the pre-monsoon spell ended",
                "dates": "Apr 18–19",
                "impact": "PM2.5 jumped from 21 to 39 on Apr 18 and stayed elevated. AQI.in dashboard showed a peak of 118 overnight into Apr 19.",
                "detail": "AQI.in's Mumbai dashboard recorded Satisfactory (72) on Apr 18 before the overnight surge. The spike pattern — sharp overnight rise followed by daytime decline — is the signature of accumulation under calm nocturnal winds and a shallow boundary layer, with daytime mixing dispersing particles. The underlying sources (construction, traffic) were persistent throughout — the only change was the weather's ability to disperse them.",
                "sources": ["AQI.in Mumbai dashboard"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-18",
                "end": "2026-04-19",
            },
            {
                "event": "Weekend rebound — PM2.5 climbed to 41 by Apr 21",
                "dates": "Apr 20–21",
                "impact": "PM2.5 rose from 27 to 41 µg/m³ — the highest reading of the second half of the month.",
                "detail": "AQI.in and Business Today forecast Mumbai AQI in the Moderate range through Apr 20-21. After the brief mid-April clean spell, steady-state dry conditions returned and PM10 climbed to 116 µg/m³ — the coarse-particle signature suggests construction and road dust resumed as the dominant drivers. The clean spells increasingly look like brief interruptions rather than a sustained trend.",
                "sources": ["AQI.in", "Business Today"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-20",
                "end": "2026-04-21",
            },
        ],
    },
    "jaipur": {
        "narrative": "Jaipur's air is shaped by the Thar Desert. PM2.5 swung from 13 to 172 µg/m³ over these 6 weeks — the widest range of any city we track. Western disturbances bring dramatic but short-lived relief; the moment rain stops, dust returns within hours. April saw the city stuck in a sustained 6-day dust spell (Apr 9–14), briefly interrupted only by the Apr 9 storm, with a second spike on Apr 20 before a one-day drop to close the period.",
        "stories": [
            {
                "event": "PM2.5 hit 172 — 11x the safe limit",
                "dates": "Mar 11",
                "impact": "The worst single day across all 6 cities. PM2.5 hit 172 µg/m³.",
                "detail": "AQICN recorded 'Unhealthy' PM2.5 levels at the Adarsh Nagar station in early March. Jaipur's proximity to the Thar Desert means windblown dust is a constant factor. IQAir identifies vehicles and industrial activity as additional sources. However, 172 µg/m³ is extreme even for Jaipur — this likely reflects a specific dust transport event, though no dust storm warning was found for this date.",
                "sources": ["AQICN", "IQAir"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-11",
            },
            {
                "event": "4 days of cleaner air during western disturbance",
                "dates": "Mar 18–21",
                "impact": "PM2.5 dropped from 48 to 28 µg/m³ over 4 days.",
                "detail": "Patrika reported IMD issued yellow alert for thunderstorms in 37 Rajasthan districts on Mar 18-19. Zee News confirmed the western disturbance was active Mar 18-21 with winds of 30-50 kmph. Jaipur Unveiled reported light rain with dust storms. Rain and wind are both effective particle removal mechanisms. The 4-day duration matches the weather system's lifespan.",
                "sources": ["Patrika", "Zee News", "Jaipur Unveiled"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-18",
                "end": "2026-03-21",
            },
            {
                "event": "PM2.5 surged to 93 in late-March heat",
                "dates": "Mar 27–28",
                "impact": "PM2.5 nearly doubled from 54 to 93 in one day — 6.2x the safe limit.",
                "detail": "EaseWeather shows end-of-March temperatures in Jaipur reach 36-37°C. Sunday Guardian's Mar 27 weather report confirms dry conditions across Rajasthan. Hot, dry conditions increase dust resuspension from unpaved surfaces — a documented mechanism in arid regions. The rapid rise is consistent with desert dust mobilization under high temperatures and low humidity.",
                "sources": ["EaseWeather", "Sunday Guardian"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-27",
                "end": "2026-03-28",
            },
            {
                "event": "Month's cleanest day — PM2.5 hit 13",
                "dates": "Mar 30",
                "impact": "For one day, Jaipur's air was within the WHO safe limit — rare for a desert city.",
                "detail": "IMD reported intermittent weather activity across Rajasthan around this time. A PM2.5 reading of 13 µg/m³ in a desert-adjacent city strongly suggests recent rainfall, as natural dust levels alone would keep readings higher. However, by Apr 1 PM2.5 was back at 75 — the relief lasted less than 48 hours.",
                "sources": ["IMD"],
                "confirmed": False,
                "type": "dip",
                "start": "2026-03-30",
                "end": "2026-03-31",
            },
            {
                "event": "Apr 9 storm brought only a one-day dip before dust returned",
                "dates": "Apr 9–14",
                "impact": "PM2.5 hit 118 on Apr 9, dropped briefly to 67 on Apr 10, then rebounded to 94–113 µg/m³ for 4 straight days.",
                "detail": "NewsX confirmed IMD warned of rain, hail, and winds up to 85 kmph across Rajasthan on Apr 9. The storm did bring scavenging — AQI.in recorded one station dropping to PM2.5 25 on Apr 10. But city-wide averages rebounded the very next day. Without a second rain event, desert dust immediately refilled the air under Jaipur's warm dry conditions — the classic Thar pattern. Over the 6-day window PM2.5 averaged 100 µg/m³, peaking at 118.",
                "sources": ["NewsX", "AQI.in"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-09",
                "end": "2026-04-14",
            },
            {
                "event": "One-day drop from 92 to 40 — no verified event",
                "dates": "Apr 20–21",
                "impact": "PM2.5 crashed 57% overnight after hovering 61–92 µg/m³ for a week.",
                "detail": "Sunday Guardian's Apr 20 weather report covered Rajasthan but recorded no specific rain event for Jaipur on these dates — April climatology shows near-zero rainfall in Jaipur, making rain-driven cleanup unlikely. A wind shift or brief gust event is a plausible mechanism (mechanical dispersion), but without ground-level weather confirmation we cannot attribute this drop to a specific cause. Noting it here as a data observation, not a confirmed event.",
                "sources": ["Sunday Guardian (IMD Apr 20 bulletin)"],
                "confirmed": False,
                "type": "dip",
                "start": "2026-04-20",
                "end": "2026-04-21",
            },
        ],
    },
    "chennai": {
        "narrative": "Chennai is the closest to safe air among the 6 cities — just 1.1x the WHO limit on average. The Manali-Ennore industrial corridor in the north drives most pollution. The story over these 6 weeks: generally clean conditions punctuated by two summer-heat spikes as Tamil Nadu's April heatwave pushed temperatures above 105°F. The city's onshore sea breeze kept a lid on most days.",
        "stories": [
            {
                "event": "Month's highest PM2.5 in early dry season",
                "dates": "Mar 10–14",
                "impact": "PM2.5 averaged 25 µg/m³ — modest by Indian standards but above the WHO limit.",
                "detail": "A peer-reviewed study in Aerosol and Air Quality Research (AAQR) documents the Manali-Ennore petrochemical corridor as a persistent SO2 and PM10 source, with the dry Jan-Mar season seeing the worst air quality citywide. The elevated March readings are consistent with this seasonal pattern. Chennai's relatively low PM2.5 compared to other Indian cities is partly due to coastal sea breeze dispersal.",
                "sources": ["AAQR journal"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-14",
            },
            {
                "event": "PM2.5 dropped to 4 µg/m³ — cleaner than most of Europe",
                "dates": "Mar 18",
                "impact": "PM2.5 hit 4 µg/m³ — for context, that's cleaner than most European cities.",
                "detail": "No specific weather event was identified. AAQR research documents that Chennai's onshore sea breeze can effectively disperse pollutants inland. A reading of 4 µg/m³ suggests strong onshore wind conditions and possibly reduced industrial/traffic activity. This is an exceptionally low reading even for Chennai.",
                "sources": ["AAQR journal"],
                "confirmed": False,
                "type": "dip",
                "start": "2026-03-17",
                "end": "2026-03-18",
            },
            {
                "event": "Late March spike near Manali industrial corridor",
                "dates": "Mar 26–28",
                "impact": "PM2.5 rose from 15 to 27 µg/m³ — the highest stretch of the month.",
                "detail": "AQI.in recorded AQI 154 (Unhealthy) at the Manali station in late March. A 2026 paper in Nature Scientific Reports documents air quality impacts from metro rail construction in Chennai. While these sources confirm elevated pollution in the industrial north, the city-wide average of 27 µg/m³ remained well below Indian NAAQS standards. The spike may reflect a combination of industrial activity and reduced sea breeze.",
                "sources": ["AQI.in", "Nature Scientific Reports"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-26",
                "end": "2026-03-28",
            },
            {
                "event": "PM2.5 rose to 32 as summer heat set in",
                "dates": "Apr 9–10",
                "impact": "PM2.5 jumped to 32 µg/m³ — AQI hit 135 (Poor). Highest of the month.",
                "detail": "AQI.in recorded AQI of 135 (Poor) on Apr 9 and 120 on Apr 10. Humidity dropped from 85% to 73% during this period — reduced moisture means less natural suppression of particulate matter. However, 32 µg/m³ is relatively mild compared to north Indian cities and is within Chennai's seasonal variability.",
                "sources": ["AQI.in"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-09",
                "end": "2026-04-10",
            },
            {
                "event": "Heatwave peaked at 104°F — PM2.5 doubled to 32",
                "dates": "Apr 18",
                "impact": "PM2.5 jumped from 9 to 32 µg/m³ in a single day — the highest reading since early March.",
                "detail": "Live Chennai reported the Tamil Nadu heatwave peaked at 104°F with temperatures 2–3°C above normal, and only limited rain expected until Apr 18. Asianet Newsable noted humidity rising as the heatwave continued. Hot, dry, and calm conditions reduce both wet deposition and vertical mixing — particulates accumulate near the surface. The spike matches the peak of the heat event.",
                "sources": ["Live Chennai", "Asianet Newsable"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-18",
                "end": "2026-04-18",
            },
            {
                "event": "Heatwave extended — 13 places above 105°F, Chennai PM2.5 at 28",
                "dates": "Apr 20–21",
                "impact": "PM2.5 climbed back to 28 µg/m³ on Apr 21 after a clean Apr 19–20 dip. PM10 also rose to 61.",
                "detail": "Live Chennai reported the Tamil Nadu heatwave extended with 13 places crossing 105°F, and rain expected only in limited areas through Apr 21. The renewed spike is consistent with the heat event — repeated heatwave days in a coastal city are unusual and push PM2.5 above Chennai's baseline. Chennai's baseline is still far below most Indian cities — but two heatwave spikes in a single month is notable.",
                "sources": ["Live Chennai"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-20",
                "end": "2026-04-21",
            },
        ],
    },
}

if __name__ == '__main__':
    import json
    with open('site_data.json') as f:
        data = json.load(f)

    for c in data:
        if c['key'] in CITY_STORIES:
            cs = CITY_STORIES[c['key']]
            c['narrative'] = cs['narrative']
            c['stories'] = cs['stories']

    with open('site_data.json', 'w') as f:
        json.dump(data, f)

    for c in data:
        stories = c.get('stories', [])
        confirmed = sum(1 for s in stories if s.get('confirmed'))
        print(f"{c['name']:<14} {len(stories)} stories ({confirmed} confirmed)")

    print(f"\nTotal: {sum(len(c.get('stories',[])) for c in data)} stories")
