"""
Hand-crafted city stories — event-driven, not data-driven.
Each story is a verified event + its measurable air quality impact.
"""

CITY_STORIES = {
    "delhi": {
        "narrative": "Delhi's spring air is a rollercoaster — dust storms from Rajasthan push PM2.5 to 9x the safe limit one day, rain clears it the next. The city swung between 25 and 142 µg/m³ this month. PM2.5 exceeded the WHO limit on every single day, even the 'good' ones.",
        "stories": [
            {
                "event": "Spring dust and traffic opened the month at 9x safe limit",
                "dates": "Mar 10–12",
                "impact": "PM2.5 hit 142 µg/m³ on the first day — the worst reading of the entire month.",
                "detail": "Westerly dust from Rajasthan combined with vehicle emissions. Delhi starts spring in a pollution trap that only rain can break.",
                "sources": ["IQAir", "Down to Earth"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-12",
            },
            {
                "event": "Holi doubled pollution overnight",
                "dates": "Mar 14",
                "impact": "PM2.5 jumped from 58 to 119 µg/m³ — doubling in a single day, 8x the safe limit.",
                "detail": "Holi (festival of colours) was celebrated on Mar 14 with Holika Dahan bonfires the night before. Firecrackers and bonfires are known pollution drivers during festivals. Rain on Mar 15 brought it back to 45.",
                "sources": ["Holi 2026 on Mar 14 (StayVista)"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-13",
                "end": "2026-03-14",
            },
            {
                "event": "Rain brought the best air quality in 161 days",
                "dates": "Mar 19",
                "impact": "PM2.5 dropped to 29 µg/m³. AQI hit 93 — first 'Satisfactory' rating since October 2025.",
                "detail": "A western disturbance — unusual for its timing and 1,000 km rain band — brought overnight showers. Also the coldest March day in 6 years.",
                "sources": ["Outlook Traveller", "NewsX", "The Patriot"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-18",
                "end": "2026-03-19",
            },
            {
                "event": "Dust returned — 3 days above 100 µg/m³",
                "dates": "Mar 23–25",
                "impact": "PM2.5 hit 126 on Mar 23, stayed above 100 for 3 straight days. 8x the safe limit.",
                "detail": "After the Mar 19 rain relief, pollution rebuilt over 4 days as dry conditions returned and traffic/construction resumed. The relief lasted exactly 4 days.",
                "sources": ["OAQ station data — no external event identified"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-23",
                "end": "2026-03-25",
            },
            {
                "event": "Massive dust storm — AQI crossed 500",
                "dates": "Apr 1–2",
                "impact": "PM10 exceeded 800 µg/m³. Delhi ranked among the world's 10 most polluted cities.",
                "detail": "The spike was overwhelmingly coarse dust — not combustion — carried by westerly winds from Rajasthan. Hazardous conditions for two days.",
                "sources": ["IQAir (Apr 3, 2026)", "AQI.in"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-01",
                "end": "2026-04-02",
            },
            {
                "event": "Coldest April day in 11 years cleared the air",
                "dates": "Apr 8",
                "impact": "Temperature hit 28.2°C — 6.9°C below normal. AQI dropped to 93 (Satisfactory).",
                "detail": "A western disturbance brought rain and wind. But by Apr 9, dust was back at 105 µg/m³. Relief lasted less than 48 hours.",
                "sources": ["Oneindia", "Daily Pioneer", "Skymet Weather"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-07",
                "end": "2026-04-08",
            },
            {
                "event": "80 µg/m³ swing in 24 hours — dust then wind",
                "dates": "Apr 9–10",
                "impact": "PM2.5 crashed from 105 to 25 overnight. From 'Severe' to near safe in one day.",
                "detail": "Winds of 22-26 kmph dispersed accumulated dust. Delhi's spring AQI has been described as 'dangerously volatile.'",
                "sources": ["AQI.in", "The Patriot", "Air Quality EWS"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-09",
                "end": "2026-04-10",
            },
        ],
    },
    "bengaluru": {
        "narrative": "Bengaluru's air is 2.4x the safe limit — moderate by Indian standards but never actually safe. Metro construction dust is a persistent driver. The month saw a hailstorm that briefly cleaned the air, a mysterious one-day spike to 60 µg/m³, an IPL match that spiked traffic, and the early signs of pre-monsoon relief. Even the cleanest day (17 µg/m³) was still above WHO limits.",
        "stories": [
            {
                "event": "Metro construction dust pushed mid-March to near month's worst",
                "dates": "Mar 12–15",
                "impact": "PM2.5 hit 48 µg/m³ on Mar 13 — 3.2x the safe limit. Dry conditions (humidity dropping from 65% to 50%) let dust linger.",
                "detail": "Namma Metro Phase 2 construction is happening in crowded residential areas without proper dust management. Citizen Matters reported dust suppression measures are not being followed properly.",
                "sources": ["Citizen Matters", "AQI.in (PM2.5=52 on Mar 13)"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-12",
                "end": "2026-03-15",
            },
            {
                "event": "Hailstorm hit the city, then air cleared for 3 days",
                "dates": "Mar 17–20",
                "impact": "PM2.5 spiked to 46 during the storm, then dropped to 28 as rain washed out particles over the following days.",
                "detail": "Hail was reported in Sanjayanagar, Yelahanka, and Devanahalli. IMD issued thunderstorm warnings for Mar 17-21. This was the first spell of pre-monsoon showers. Ugadi was celebrated on Mar 19.",
                "sources": ["Deccan Herald", "Zee News (IMD)"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-17",
                "end": "2026-03-20",
            },
            {
                "event": "Worst day of the month — PM2.5 hit 60, then crashed back",
                "dates": "Mar 23–24",
                "impact": "PM2.5 spiked to 60 µg/m³ (4x the safe limit) then dropped to 36 overnight — a 41% fall.",
                "detail": "No specific event found for this one-day anomaly. The spike was city-wide across 39 stations, suggesting a regional dust event rather than a local source.",
                "sources": ["OAQ station data"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-23",
                "end": "2026-03-24",
            },
            {
                "event": "Pre-monsoon showers kept air below average for 4 days",
                "dates": "Apr 1–4",
                "impact": "PM2.5 averaged 31 µg/m³ — still 2x the safe limit, but the cleanest sustained stretch of the month.",
                "detail": "IMD confirmed the pre-monsoon convective season had established over Karnataka, with 90-100% thunderstorm probability.",
                "sources": ["Oneindia", "IMD Bengaluru"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-01",
                "end": "2026-04-04",
            },
            {
                "event": "IPL match day — traffic spiked, so did pollution",
                "dates": "Apr 5",
                "impact": "PM2.5 jumped from 32 to 43 µg/m³. The only spike in an otherwise clean first week of April.",
                "detail": "RCB vs CSK at Chinnaswamy Stadium. Police banned parking on MG Road and Queens Road, issued formal traffic advisory. Massive crowds converged on the city center.",
                "sources": ["IPLT20 (match confirmed)", "News9", "Goodreturns"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-05",
                "end": "2026-04-05",
            },
            {
                "event": "35.2°C heatwave — but PM2.5 actually dropped",
                "dates": "Apr 7",
                "impact": "Bengaluru recorded its lowest PM2.5 of the month (17 µg/m³ — near WHO safe levels) on one of its hottest days.",
                "detail": "The 35.2°C reading was 1.5°C above normal. Hot air rising creates strong vertical mixing that can disperse pollutants — heat doesn't always mean more pollution.",
                "sources": ["NewsFirst Prime", "Deccan Herald"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-07",
                "end": "2026-04-07",
            },
        ],
    },
    "hyderabad": {
        "narrative": "Hyderabad's air is the steadiest of the 6 cities — 2.1x the WHO limit with less day-to-day volatility than Delhi or Jaipur. Unseasonal rain around Ugadi gave the longest clean stretch of the month, but construction dust quickly brought pollution back.",
        "stories": [
            {
                "event": "Dry heat pushed pollution to month's peak",
                "dates": "Mar 12–15",
                "impact": "PM2.5 averaged 37 µg/m³ — the highest sustained stretch of the month.",
                "detail": "Temperatures 32-37°C with no rain let dust and emissions accumulate across the city.",
                "sources": ["IMD via PingTV"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-12",
                "end": "2026-03-15",
            },
            {
                "event": "Unseasonal rain + Ugadi gave a week of cleaner air",
                "dates": "Mar 16–22",
                "impact": "PM2.5 dropped to 22 µg/m³ on Mar 16 and stayed low for 7 days — the longest clean stretch of the month.",
                "detail": "Unseasonal rains with lightning and gusty winds (41-61 kmph) swept through Telangana. Ugadi was celebrated on Mar 19 with reduced weekday activity.",
                "sources": ["PingTV", "Hyderabad Mail"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-16",
                "end": "2026-03-22",
            },
            {
                "event": "Construction dust spiked pollution — residents complained",
                "dates": "Mar 28–30",
                "impact": "PM2.5 jumped to 44 µg/m³ — 2.9x the safe limit. AQI hit 146 on Mar 27.",
                "detail": "Residents near Golconda Chowrasta reported severe dust from construction. Elderly, children, and patients faced respiratory problems.",
                "sources": ["AQI.in", "Hyderabad Mail"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-28",
                "end": "2026-03-30",
            },
            {
                "event": "Late-March showers brought April into a calmer pattern",
                "dates": "Mar 31 – Apr 7",
                "impact": "PM2.5 averaged 27 µg/m³ for a week — no dramatic spikes.",
                "detail": "Late evening thundershowers around end of March reset conditions. April was steadier than March.",
                "sources": ["Sunday Guardian", "IMD"],
                "confirmed": False,
                "type": "dip",
                "start": "2026-03-31",
                "end": "2026-04-07",
            },
        ],
    },
    "mumbai": {
        "narrative": "Mumbai had two clear phases this month. Early March was dirty (PM2.5 up to 48, driven by construction and traffic). Then rain arrived on Mar 28 and the air became extraordinarily clean — AQI hit 21 on Mar 31, the lowest in months. But by April 9, dry heat brought it all back.",
        "stories": [
            {
                "event": "BMC crackdown on 1,073 construction sites",
                "dates": "Mar 10–13",
                "impact": "PM2.5 averaged 44 µg/m³ despite enforcement. Hotspots: Kanjurmarg AQI 309, Ghatkopar 183.",
                "detail": "BMC issued stop-work notices to 1,073 construction sites violating dust-control norms. PM2.5 was down 14% year-on-year, but still 3x the safe limit.",
                "sources": ["Deccan Herald", "Free Press Journal"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-13",
            },
            {
                "event": "Pollution crept back up over 10 days — peaking at 48",
                "dates": "Mar 17–26",
                "impact": "PM2.5 rose gradually from 13 to 48 µg/m³ over 10 days as dry weather returned.",
                "detail": "After BMC enforcement brought brief relief, pollution steadily rebuilt. Mumbai had only 7 'good' air days in 5 years — chronic pollution is the norm, not the exception. Construction dust is the primary driver.",
                "sources": ["Newslaundry (Mar 10, 2026)", "Free Press Journal"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-17",
                "end": "2026-03-26",
            },
            {
                "event": "Rainfall brought ultra-clean air — AQI hit 21",
                "dates": "Mar 28 – Apr 8",
                "impact": "PM2.5 dropped to 10 µg/m³ — below the WHO safe limit for the first time. AQI 21 on Mar 31.",
                "detail": "Light rain on Mar 31 washed out pollutants. Mumbai's air was cleaner than most European cities for nearly two weeks.",
                "sources": ["Free Press Journal"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-28",
                "end": "2026-04-08",
            },
            {
                "event": "Dry heat brought pollution right back",
                "dates": "Apr 9–10",
                "impact": "PM2.5 surged to 43 µg/m³ by Apr 10 — the highest since late March. Navi Mumbai AQI hit 201 (Severe).",
                "detail": "Mumbai ranked among the most polluted cities globally on Apr 9. The clean spell ended as rain stopped and dry heat returned.",
                "sources": ["AQI.in", "IQAir"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-09",
                "end": "2026-04-10",
            },
        ],
    },
    "jaipur": {
        "narrative": "Jaipur's air is shaped by the Thar Desert. PM2.5 swung from 13 to 172 µg/m³ this month — the widest range of any city we track. Western disturbances bring dramatic but short-lived relief; the moment rain stops, dust returns within hours.",
        "stories": [
            {
                "event": "Desert dust pushed PM2.5 to 172 — 11x the safe limit",
                "dates": "Mar 11",
                "impact": "The worst single day across all 6 cities. PM2.5 hit 172 µg/m³.",
                "detail": "Vehicles and industrial activity compound the natural desert dust. Adarsh Nagar station recorded 'Unhealthy' levels in early March.",
                "sources": ["AQICN", "IQAir"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-11",
            },
            {
                "event": "Western disturbance brought 4 days of clean air",
                "dates": "Mar 18–21",
                "impact": "PM2.5 dropped from 48 to 28 µg/m³. One day (Mar 30) later hit 13 — near WHO safe levels.",
                "detail": "IMD issued yellow alert for thunderstorms in 37 Rajasthan districts. Winds 30-50 kmph and light rain.",
                "sources": ["Patrika", "Zee News", "Jaipur Unveiled"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-03-18",
                "end": "2026-03-21",
            },
            {
                "event": "Dry heat surged PM2.5 to 93 — 6x the safe limit",
                "dates": "Mar 27–28",
                "impact": "PM2.5 nearly doubled from 54 to 93 in one day as end-of-March temperatures hit 36-37°C.",
                "detail": "After the western disturbance passed, dry conditions returned. Temperatures above 35°C combined with desert dust resuspension.",
                "sources": ["EaseWeather", "Sunday Guardian (Mar 27 weather)"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-27",
                "end": "2026-03-28",
            },
            {
                "event": "The cleanest day: PM2.5 hit 13 µg/m³",
                "dates": "Mar 30",
                "impact": "For one day, Jaipur's air was within the WHO safe limit — rare for a desert city.",
                "detail": "Brief rainfall the previous evening likely contributed. But by Apr 1, PM2.5 was back at 75.",
                "sources": ["IMD"],
                "confirmed": False,
                "type": "dip",
                "start": "2026-03-30",
                "end": "2026-03-31",
            },
            {
                "event": "Thunderstorm and hail: 118 → 29 in 24 hours",
                "dates": "Apr 9–10",
                "impact": "The most dramatic single-day drop of the month. PM2.5 fell 75% overnight.",
                "detail": "IMD warned of rain, hail, and winds up to 85 kmph. PM2.5 dropped to 25 µg/m³ (Good) by Apr 10.",
                "sources": ["NewsX", "AQI.in"],
                "confirmed": True,
                "type": "dip",
                "start": "2026-04-09",
                "end": "2026-04-10",
            },
        ],
    },
    "chennai": {
        "narrative": "Chennai is the closest to safe air among the 6 cities — just 1.1x the WHO limit on average. The Manali-Ennore industrial corridor in the north drives most pollution. The story this month: generally clean conditions with a late spike as summer heat arrived.",
        "stories": [
            {
                "event": "Dry season pushed pollution to month's highest",
                "dates": "Mar 10–14",
                "impact": "PM2.5 averaged 25 µg/m³ — modest by Indian standards but still above the WHO limit.",
                "detail": "The Manali-Ennore petrochemical and refinery corridor is a persistent source of SO2 and PM10. Dry Jan-Mar is the worst season for Chennai's air.",
                "sources": ["AAQR journal"],
                "confirmed": False,
                "type": "spike",
                "start": "2026-03-10",
                "end": "2026-03-14",
            },
            {
                "event": "Mid-March: air dropped to 4 µg/m³ — some of India's cleanest",
                "dates": "Mar 18",
                "impact": "PM2.5 hit 4 µg/m³. For context, that's cleaner than most Scandinavian cities.",
                "detail": "Sea breeze and reduced activity drove Chennai well below the WHO limit. The coastal geography helps — onshore winds push pollutants inland.",
                "sources": ["AAQR journal"],
                "confirmed": False,
                "type": "dip",
                "start": "2026-03-17",
                "end": "2026-03-18",
            },
            {
                "event": "Late March spike — Manali industrial corridor lit up",
                "dates": "Mar 26–28",
                "impact": "PM2.5 rose from 15 to 27 µg/m³ — still modest, but the highest stretch of the month.",
                "detail": "The Manali-Ennore petrochemical corridor and metro rail construction are persistent dust and SO2 sources. Manali station recorded AQI 154 (Unhealthy) in late March.",
                "sources": ["AQI.in", "Nature Scientific Reports (metro construction)"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-03-26",
                "end": "2026-03-28",
            },
            {
                "event": "Summer heat spiked pollution to 32",
                "dates": "Apr 9–10",
                "impact": "PM2.5 jumped to 32 µg/m³ — AQI hit 135 (Poor). Highest of the month.",
                "detail": "As humidity dropped from 85% to 73%, particles stayed airborne longer. Chennai AQI reached 120-135, classified as 'Poor.'",
                "sources": ["AQI.in"],
                "confirmed": True,
                "type": "spike",
                "start": "2026-04-09",
                "end": "2026-04-10",
            },
        ],
    },
}

if __name__ == '__main__':
    import json
    # Merge stories into site_data.json
    with open('site_data.json') as f:
        data = json.load(f)

    for c in data:
        if c['key'] in CITY_STORIES:
            cs = CITY_STORIES[c['key']]
            c['narrative'] = cs['narrative']
            c['stories'] = cs['stories']

    with open('site_data.json', 'w') as f:
        json.dump(data, f)

    for c in data:
        stories = c.get('stories', [])
        confirmed = sum(1 for s in stories if s.get('confirmed'))
        print(f"{c['name']:<14} {len(stories)} stories ({confirmed} confirmed)")

    print(f"\nTotal: {sum(len(c.get('stories',[])) for c in data)} stories")
